### ISSUE TITLE
Read the meeting note!!!

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#108]
It is crucial for all to read this document.
https://github.com/bounswe/bounswe2017group1/wiki/Meeting-12---02-11-2017
Please ask any question that you have about the assignments and stick with the deadlines.

I strongly suggest frontend and android teams also do a meeting between the team.

**Comment by frknilisu** [comment]
I really like my task

**Comment by mrceyhun** [comment]
OK, I got it. :running::running::running::running::running::running::running:
