### ISSUE TITLE
To do list till the meeting this Thursday(16 February)

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#11]
Every project member should **read and more importantly absorb the project description in Cultural Heritage Pdf**. Optimally every Group-1 member should think about the possible requirements draft before the meeting and for that purpose **please read the pdf at least twice before the preceding night of our meeting**. So that you can think about it the fallowing day before the meeting.
If you can't do that every member at least shall read it before the meeting.
[projectdescription.pdf](https://github.com/bounswe/bounswe2017group1/files/774352/projectdescription.pdf)

Ps: if you guys have anything else in your mind that we should consider or add, please comment.

**Comment by mehmetsefa2644** [comment]
We can add the things that we see important about project to [the wiki page that I created ](https://github.com/bounswe/bounswe2017group1/wiki/Project-Description-Summary).
So things would be clear when we meet.
