### ISSUE TITLE
Github usage statistics

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#110]
I just realized that statistics in the "Insights" bar done in Github are based on the master branch. But sadly we did all of the development in "web" and since we did all the development in "web" branch, current statistics are misleading. To clarify this possible confusion we will do a merge to master in later today.  

Sorry for the inconvenience

**Comment by hakansirin** [comment]
merge is done sir @cihatbaktir

**Comment by cihatbaktir** [comment]
Thank you for the fix. Now the issue can be closed and marked as completed.
