### ISSUE TITLE
Meeting-2 for Assignment-3(Requirements) Task Sharing

### ISSUE THREAD

**Issue by mrceyhun** [bounswe/bounswe2017group1#12]
As we decided in our last meeting, we will share the jobs for requirements of  the Cultural Heritage Project between the ones in the meeting. There are five main jobs. If another title apart from these jobs will come to your mind, you can add new job description.  The deadline of these jobs is 18 Feb. 2017, Saturday evening. We will evaluate each part in Saturday evening.

- [@hakansirin , @uvut ] **Requirements of adding a new heritage item by users:**

    In this part when a user want to add a new heritage item, what kinds of requirements will occur. 

- [@mustafafeyzioglu , @mehmetgulsen ] **Requirements of annotations:**
    
    Annotations is one of the important part of our project. There are some kinds of annotations and each of their application processes will results for new requirements. 

- [@mrceyhun, @tahabayi] **Requirements for search mechanism:**
    
    Searching of mainly heritage items and other things is one of the requirements of the project. There will be some requirements under the title of it.

- [@mehmetsefa2644 , @frknilisu] **Requirements of API of the project and protocols that we should obey:**

    There will be an API in our project. Therefore, there will be some requirements in creating the architecture of the API. Also, one of our given requirement is some protocols that we should obey and implement the API according to them.

- [ not given ] **Authantication requirements:**

**Comment by mehmetsefa2644** [comment]
Will we prepare both user and system requirements?

**Comment by mrceyhun** [comment]
Functional Requirements: [https://en.wikipedia.org/wiki/Functional_requirement](https://en.wikipedia.org/wiki/Functional_requirement)

Non-functional Requirements: [https://en.wikipedia.org/wiki/Non-functional_requirement](https://en.wikipedia.org/wiki/Non-functional_requirement)

When we are writing our parts of requirements, it will be good if we keep our mind these two descriptions.
