### ISSUE TITLE
Heritage item creator name

### ISSUE THREAD

**Issue by tahabayi** [bounswe/bounswe2017group1#121]
Heritage items do not return creator name of heritage. Creator name of heritage items will be displayed on the main page, so we need that field too.

**Comment by hakansirin** [comment]
I am working on it. I plan to add the field in the returned json item as "creator_name". I will let you know again when it is working in the amazon server. 
Regards,
HS

**Comment by hakansirin** [comment]
![image](https://user-images.githubusercontent.com/13136199/32979038-e562ef5e-cc5e-11e7-8774-5dbf8ee28377.png)
It is gonna be working like this. Still not running on amazon :)

**Comment by hakansirin** [comment]
I change the model a bit it is now working in amazon port 3000. An example of a request is as follows. 
![image](https://user-images.githubusercontent.com/13136199/32982801-3f3ffd1e-cc9b-11e7-9b5e-d0e83367af38.png)
