### ISSUE TITLE
ConceptNet crashes

### ISSUE THREAD

**Issue by mehmetgulsen** [bounswe/bounswe2017group1#128]
ConceptNet API keeps crashing. We are getting "502 Bad Gateway" error every so often. It gets back online in around 20 minutes but this could be problematic.

Our options are either running our own copy of the API, finding another API, or giving up using an external API.

How do you think we should resolve this?

**Comment by hakansirin** [comment]
It is not really clear to whom you are asking this question but i am gonna answer it anyway. 
As discussed in the whatsapp group we can create a copy of the service in an amazon instance. It would need a stronger server than the free tier student amazon account but it is not a really big deal if we come to a point without any other possible solution. The rent of an amazon server with the strength we need would cost us less than 5 dollars for the duration of the ConceptNet service build + the necessary test + the milestone presentation. 
ConceptNet is a well documented Opensource service as you know and what I offer might be hard to do but totally doable. 
Here it tells how to do it and an amazon t2.medium server is enough which costs less than 5 cents an hour. 
https://github.com/commonsense/conceptnet5/wiki/Running-your-own-copy

And we can always keep the presentation going with a prerecorded video in case of a server failure.

Regards,
Hakan

**Comment by mehmetgulsen** [comment]
5 dollars is for 100 hours right? So your suggestion is to keep it as it is until the presentation day is near, and then switch to our own copy when we need to make a presentation to keep the expanses low? I'm OK with it.

**Comment by hakansirin** [comment]
It is probably better if we can find a more reliable api which we can use without all of these troubles but what i am saying is the worst case isn't that bad.

**Comment by frknilisu** [comment]
I found the below site for alternative to ConceptNet API:
http://www.rhymezone.com
please look and try it and give feedbacks

**Comment by mehmetgulsen** [comment]
It looks even easier to use than ConceptNet, and it is the best alternative I have seen so far. But I'm not really sure if the results are good enough.

This is the first 10 result when I tried to search related items for"game":

1. punt
2. back
3. gritty
4. gamey
5. gage
6. fearless
7. spirited
8. spunky
9. stake
10. mettlesome

If you guys think it is good enough, I can adjust the code easily.

**Comment by mehmetgulsen** [comment]
We have decided on using the Datamuse API that rhymezone.com uses.
