### ISSUE TITLE
Image api usage for Media service

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#133]
Hello all,
Our media service is up and running in the amazon server now. And documentation will be coming soon by @alpbildik but since there is really limited time to this week`s mini milestone I wanted to give you a heads up beforehand. 
Because of the form restrictions we had to use different form than json(Json does not accept files) and again because of that and the many to many relationship between madia and heritage, we have to get one additional request for each media file you want to add to heritage. 

Here I will show example usages:
example header of the request 
![image](https://user-images.githubusercontent.com/13136199/33085302-62848860-cef5-11e7-9754-94e637e22922.png)

Body of the same request 
![image](https://user-images.githubusercontent.com/13136199/33085317-70a6e2ee-cef5-11e7-8692-e84ccd4f636f.png)

and the same heritage item get request result after these media create request

![image](https://user-images.githubusercontent.com/13136199/33085365-92a17292-cef5-11e7-808e-d4325d68366b.png)

For delete you only need to send delete req instead of post to the same url.

Regards,
Hakan

**Comment by alikirec** [comment]
File upload service is can be used in web page except for a little bug, I thin the front end part is ok

**Comment by hakansirin** [comment]
It was working fine except little formatting issue. 
I think it is a better to use the photo without changing the ratio of pixel.
