### ISSUE TITLE
Item Detail View UI

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#143]
UI in item detail view should be beautified, 
Mockups should guide us during the beautification.
- [x]  Fix creator name,
- [x] Align imageView,
- [x] Add tags

#### Due: 28/11/2017

**Comment by mehmetsefa2644** [comment]
- [ ]  Fix creator name,
- [ ] Align imageView,
- [ ] Add tags

**Comment by hakansirin** [comment]
Issue usage gone crazy!!!

**Comment by mehmetsefa2644** [comment]
The UI of the detail view is satisfactory now, we can reopen this issue if necessary
