### ISSUE TITLE
Heritage update tag service bug 

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#151]
There is a bug in current edit tag service for heritage items. It only supports additions of new tags.

For instance if we originally create an heritage item with 3 tags and then make a put request with only 2 of these tags. The item will still have all 3 tags. But when we add a new tag in put request the heritage will have that also.

The way it should work is heritage item should have the tags only sent in the put request regardless of the previous tags. It is also important to check for if there is an existing tag with the same new. So that not to have more than one tag in the DB with the same name.(currently this part works as expected.)

**Comment by alpbildik** [comment]
Fixed and done: we can close the issue
https://github.com/bounswe/bounswe2017group1/pull/202
