### ISSUE TITLE
Tag.related_list always returns null

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#156]
It should have been returning the list returned from the API but it is not the case. I checked if the ConceptNet API is working and it was so the problem is on our end. Please fix this soon. Otherwise my database creation would be meaningless

**Comment by hakansirin** [comment]
By the way there is no application purpose of returning that list to user. 
We can mark that as TODO

**Comment by mehmetgulsen** [comment]
Done. I have made a new pull request for it: #173
