### ISSUE TITLE
Vote deletion

### ISSUE THREAD

**Issue by basriyilmazturk** [bounswe/bounswe2017group1#159]
In our system, our users can upvote/downvote an item. But (right now) it is not possible to undo/revert given vote point. We need a rest api call that can handle vote deletion functionality.

**Comment by hakansirin** [comment]
Done darling 
![image](https://user-images.githubusercontent.com/13136199/33183671-d94952ba-d089-11e7-8cf3-86d832269ec6.png)

#170 is connected to this issue
