### ISSUE TITLE
Mock-Up - Create a Mock-Up

### ISSUE THREAD

**Issue by erkan309** [bounswe/bounswe2017group1#16]
# What needs to be done:

- create a Mock-Up Template for our Project 
- create a Mock-Up for Firefox Browser
- create a Mock-Up for a Android Mobilphone

### Assignees should attend to the mock-up channel in slack.

**Comment by hakansirin** [comment]
Please assign yourselves to this group if you are not in the requirements task. Therefore we can know  you are on track with rest of us.

**Comment by mehmetsefa2644** [comment]
1- I will create a group for mock-up in slack. So we can communicate and do the mock up efficiently. 
2- What is the due date for the mock up? We should add the due date to the issue.

**Comment by tahabayi** [comment]
There is a mock-up channel in slack.

**Comment by mehmetsefa2644** [comment]
ok, I just saw that . Assignees should attend to that channel

**Comment by tahabayi** [comment]
The due date of mock-up is 28.02.2017 until the lecture hour.

**Comment by mehmetsefa2644** [comment]
Ok, I am adding the due date to the issue and closing the comments for clear view. 
Thanks
