### ISSUE TITLE
Voting in Item Detail View

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#164]
- [x] Add upvote downvote buttons to the item detail view,
- [ ] Make them functional

#### Due: 30/11/2017 - 09:00

**Comment by mehmetsefa2644** [comment]
The upvote and downvote buttons are added, thanks to @mustafafeyzioglu . 
We should now only make them functional.

**Comment by mustafafeyzioglu** [comment]
Voting functionality is done
