### ISSUE TITLE
Requirements - Necessary edit before consumer feedback !!!URGENT!!!

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#17]
We need to revise the requirements pdf before the consumer feedbacks on Friday 24 February. 
So the deadline for this revise is before tomorrows weekly meeting. I plan to divide the work between 3 of us later tonight. Since than you can still work on requirements as your will.

**Comment by hakansirin** [comment]
**task 1:**
fill the glossary items.
**task 2:**
finish requirement 1.2.3(decsribe search procedure)
**task 3:** 
overview all requirements (typos, misleading info etc) and think about possible more headlines to add. We are gonna talk about it in the weekly meeting.

@mehmetgulsen @frknilisu @mrceyhun 

**Please pick one of these 3 tasks and let others know under this issue!!!**

Regardless of which task you choice please overview the whole requirements, we can decide on further details in the weekly meeting.

**Comment by mehmetgulsen** [comment]
Sounds good. I will be taking on the task 2.

**Comment by mrceyhun** [comment]
I am taking the task 3. Also, I can contribute to other tasks, if I can find something helpful.
