### ISSUE TITLE
Homepage Tabs functionality is ready for use

### ISSUE THREAD

**Issue by mehmetgulsen** [bounswe/bounswe2017group1#176]
You can implement the "new", "top", "trending" tabs in homepage when you have the time.

You just need to send your GET requests to "/items/new" etc. instead of "/items/". The response style is the same, they're just sorted.

This is of low priority. Just do it whenever you can. "/items/" is still working so your existing stuff shouldn't break.

**Comment by mehmetsefa2644** [comment]
Thanks, great work
![bitmoji](https://render.bitstrips.com/v2/cpanel/3a6f1168-674c-4c8f-b8e8-4218d74d7570-f1d5da82-6d55-48a1-869a-a538c730fc02-v1.png?transparent=1&palette=1&width=246)
