### ISSUE TITLE
Android Tabular View in Main Activity

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#179]
We have to implement the tabular format in Main Activity to sort the items.
Mehmet implemented a good API for us. Please see #176

**Comment by mehmetsefa2644** [comment]
we will probably add fragment to the main activity and list the heritage items in that fragment, 
when the sort of the items is change via dropdown menu, we will update the fragment.

**Comment by mustafafeyzioglu** [comment]
I will do some researches on this issue

**Comment by mustafafeyzioglu** [comment]
Done.
