### ISSUE TITLE
Mock-Up Scenarios and Task Distribution

### ISSUE THREAD

**Issue by uvut** [bounswe/bounswe2017group1#18]
For the guys who will work on Mock-ups. Please choose one of the scenarios listed below. Assing yourself to issue and comment about the scenario you choose.

**Scenario 1**
User opens the website. Logs in. Creates a new heritage item. Adds an annotation (2-3 people)

**Scenario 2**
An unregistered user opens the website. Searches for an item. (1-2 people)

**Scenario 3**
Registered user adds an annotation via using plug-in. (1-2 people)

**Scenario 4**
A user searchs an item and views it by using the anroid app. (1-2 people)

**Comment by mehmetsefa2644** [comment]
I assign myself to the 4th scenario.

**Comment by mrceyhun** [comment]
I am taking the 2nd scenario.

**Comment by mrceyhun** [comment]
Which software we will use. Are there any suggestion?

**Comment by mustafafeyzioglu** [comment]
I assign myself to the 1st and 3rd scenarios since these are interrelated. Anybody can help me for  this task?

**Comment by mustafafeyzioglu** [comment]
We can use [https://ninjamock.com/](url) for creating Mock-Ups
