### ISSUE TITLE
AppBar bugs and adding search bar

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#190]
There are bugs in AppBar, In MainActivity appbar shows back button, back button should be removed and we should add search box to the appbar.

In addition to these, AppBar should be only in MainActivity and we should remove AppBar from other activities

#### Due: 01.12.2017 17:00

**Comment by mehmetsefa2644** [comment]
Search box is added to appbar. 
Back Button should be removed from appbar in main activity, and appbar in other activities should be removed.

**Comment by mustafafeyzioglu** [comment]
Up/home button is removed and action bar is hidden in detail view
