### ISSUE TITLE
Android upvote/downvote refresh bug

### ISSUE THREAD

**Issue by tahabayi** [bounswe/bounswe2017group1#194]
- [ ] Upvoting/downvoting a heritage item in detail view refreshing page instead of just refreshing buttons view

**Comment by mehmetsefa2644** [comment]
Right, we should fix it

**Comment by hakansirin** [comment]
#212 after this pull request you can use the fields in the returned JSON for your POST votes and DELETE votes requests. 
I also updated the documentation for you convenience.
https://github.com/bounswe/bounswe2017group1/blob/web/web/api/README.md
check votes part

**Comment by mustafafeyzioglu** [comment]
done
