### ISSUE TITLE
User Avatars

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#195]
We should display user avatars in heritage item list, and comment list.

#### Due: 05.12.2017 17:00

**Comment by mehmetsefa2644** [comment]
@hakansirin  @frknilisu , Please inform us after you implemented the corresponding API functionality. So we can implement this issue.

**Comment by mehmetsefa2644** [comment]
Default avatar is added by @mustafafeyzioglu . Real avatars will be added after API implementation is done.

**Comment by hakansirin** [comment]
#212 you can use the "creator_image_path" parameters in heritage item and comment api requests after the merge of this pull request. 
Sefa you can close the issue after you connect the android ends to creator_image_path variable

**Comment by mustafafeyzioglu** [comment]
Done.
