### ISSUE TITLE
Meaningful Heritage Items For Demo

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#196]
I think we should update the database such that we have meaningful heritage items in database for the sake of demonstration on demo. What do you think?

**Comment by mrceyhun** [comment]
I will create meaningful heritage items with sound, reasonable data till this Saturday(2 December) night.
As we speak today, anyone can contribute, and more team contribution make our website more attractive.

**Comment by mrceyhun** [comment]
Is it a problem to delete current unmeaningful (just used for test) data in AWS when I create new heritage items in Saturday.  @mehmetsefa2644

**Comment by hakansirin** [comment]
No problem my friend

**Comment by mehmetsefa2644** [comment]
@mrceyhun  sure, you can delete the current dummy items
![bitmoji](https://render.bitstrips.com/v2/cpanel/43533bc8-de9f-4e89-9f7d-f9a64b6254c4-f1d5da82-6d55-48a1-869a-a538c730fc02-v1.png?transparent=1&palette=1&width=246)

**Comment by hakansirin** [comment]
![image](https://user-images.githubusercontent.com/13136199/33505854-39808a84-d6fe-11e7-847d-07ded45eb651.png)
Did you mean picture here?

**Comment by mrceyhun** [comment]
I mean secondary meaning of "sound" as an adjective, not as an object name.

**Comment by mrceyhun** [comment]
I created more than 15 meaningful heritage items.

*    These items contains **building**, **food**, **historical person**, **places** from Spain, Italy, Peru,
Germany, France.
*    Dates are meaningful
*    Location contains country and city(if exists). 

If you need  a user to signin:

**Users & Passwords:**
Daniela Bianchi : DB123456
Albert Camus : AC123456
Marie Curie : MC123456
Petra Schwille : PS123456 
Ella Marija : EM123456
James Watson : JW123456
christina ochoa : CO123456
Angel Rodriguez Lozano : ARL123456
Mohamed Zidan : MZ123456
Martin Mejia : MM123456

ALL your **COMMENTS** and **UPVOTES** are awaiting.  ![bitmoji](https://render.bitstrips.com/v2/cpanel/9941574-270452369_2-s1-v1.png?transparent=1&palette=1&width=300)
