### ISSUE TITLE
Item Seach View

### ISSUE THREAD

**Issue by mustafafeyzioglu** [bounswe/bounswe2017group1#198]
- [x] Add Search Box to the Action Bar 
- [x] Create Search Results page
- [x] Make them functional 
- [x] Integrate avatars
#### Due: 06.12.2017 23:55

**Comment by mustafafeyzioglu** [comment]
search box is added on action bar

**Comment by mehmetsefa2644** [comment]
Thanks bro, I tried the search box, it works like a charm, and I just began implementing search feature.
![bitmoji](https://render.bitstrips.com/v2/cpanel/2e701e39-8580-47e6-b8fc-476a868fe446-f1d5da82-6d55-48a1-869a-a538c730fc02-v1.png?transparent=1&palette=1&width=246)

**Comment by mehmetsefa2644** [comment]
Search functionality is done. But we should integrate avatars after #195 is implemented and then merge the search branch.

**Comment by mehmetsefa2644** [comment]
Avatars are integrated, thanks to @mustafafeyzioglu .  Default avatars are added in #211 . and search functionality is added in #208 .
