### ISSUE TITLE
Avatar images

### ISSUE THREAD

**Issue by mrceyhun** [bounswe/bounswe2017group1#200]
Find and install new avatars for the usage of user images.

**Comment by mrceyhun** [comment]
New avatar images are added to folder web/avatars in WEB branch.

**Comment by hakansirin** [comment]
This issue is not quite closed my friend. We need genderless and somewhat culture related avatars :)

**Comment by mrceyhun** [comment]
I could not find both genderless and cultural related avatars, but I added genderless avatars. 
There exists in **web branch**.
