### ISSUE TITLE
We need to take action after the feedback from Suzan Hoca 

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#227]
As you can see here Suzan Hoca created an item here but also has some complaints.
http://ec2-18-196-2-56.eu-central-1.compute.amazonaws.com/item/92 
-We need to show the Location in Heritage Item detail view. 
-And the returning site after the edit should be the edited post itself.
![image](https://user-images.githubusercontent.com/13136199/33795833-c811c8a2-dcf9-11e7-9f2e-3e43d950aa03.png)

**Comment by mehmetgulsen** [comment]
How did you even see her comment from all those heritages? Were you just checking items randomly or did she tell you to check her comments? If she didn't tell you, nice catch!

**Comment by hakansirin** [comment]
Remember... We have a new items feed

**Comment by alikirec** [comment]
The problems mentioned fixed except we do not point the location on map because it looks bad on page
