### ISSUE TITLE
Recommending System Requirements

### ISSUE THREAD

**Issue by mehmetgulsen** [bounswe/bounswe2017group1#24]
Please add a section in the requirements wiki page, explaining a recommending system.

We can create a relation between the heritage items via annotations, semantic tagging etc. If I add a comment to a heritage, the system may recommend me a similar content. There are important aspects with respect to recommendation.

**Comment by hakansirin** [comment]
i got this

**Comment by hakansirin** [comment]
it still needs reviews but done for now. I am open to any further opinions about how should it work
