### ISSUE TITLE
Use Cases, tasks sharing.

### ISSUE THREAD

**Issue by mrceyhun** [bounswe/bounswe2017group1#29]
As we all know, we should create user stories for our project. We spoke about what kinds of stories we can form in the meeting. If anyone add extra story, it can be beneficial.

These are the stories that we spoke:
1-) User log in
2-) Sign up new user
3-) Create a new heritage item
4-) Make an annotation to an existing heritage item
5-) Share a heritage item via Twitter, Facebook, etc.
6-) Search a heritage item

Choose one of them, self-assign yourself and indicate what you selected.

**Comment by mrceyhun** [comment]
I am selecting first and second tasks. 1 and 2.

**Comment by mustafafeyzioglu** [comment]
I select sixth use case scenario.

**Comment by mehmetgulsen** [comment]
I choose the 3rd use case.

**Comment by tahabayi** [comment]
I got 4th use case.

**Comment by mustafafeyzioglu** [comment]
Done.
