### ISSUE TITLE
api research

### ISSUE THREAD

**Issue by mehmetgulsen** [bounswe/bounswe2017group1#3]
Make some research on an API and create a wiki page for it.

PS: I do realize there is already an issue for this and that I can assign myself to it. This issue is created to meet the requirements of the Assignment 2.

**Comment by hakansirin** [comment]
here is the related wiki 
https://github.com/bounswe/bounswe2017group1/wiki/API-Research

**Comment by mustafafeyzioglu** [comment]
Done.
