### ISSUE TITLE
Class Diagrams

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#32]
We should complete the class diagrams.

**Comment by hakansirin** [comment]
Class Diagram is complete

**Comment by hakansirin** [comment]
[uml.pdf](https://github.com/bounswe/bounswe2017group1/files/836023/uml.pdf)

**Comment by hakansirin** [comment]
![uml](https://cloud.githubusercontent.com/assets/13136199/23825835/22926692-069a-11e7-90b0-be0c7772baff.png)

**Comment by hakansirin** [comment]
![uml 1](https://cloud.githubusercontent.com/assets/13136199/23825999/11d1c14c-069d-11e7-8567-5a8f8528c908.png)

little revision
