### ISSUE TITLE
Sequence Diagram - draw a few Sequence Diagram

### ISSUE THREAD

**Issue by erkan309** [bounswe/bounswe2017group1#33]
Sequence Diagram for: 

1. Login
2. Comment
3. edit Heritage Item
4. Annotation

Pick one and draw it. I selected number 4 and drawn.

**Comment by mrceyhun** [comment]
I selected second one.

**Comment by hakansirin** [comment]
#42 #44 #46 
It is divided to 3 issue. So this one is not needed anymore
