### ISSUE TITLE
Design Tasks

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#35]
Defining the design period tasks. Deadline: next lecture.

**Comment by mehmetsefa2644** [comment]
@uvut, when the design tasks are ready, please add the link to the design tasks file to [the gant chart issue](https://github.com/bounswe/bounswe2017group1/issues/39) as comment.

**Comment by hakansirin** [comment]
@uvut  new deadline is Saturday midnight.
Each task should have these properties:
1-Start Date
2-Finish Date
3-Duration(day)
3-How many people(optional)
As Sefa said add the link to their issue #39 when you are done
