### ISSUE TITLE
Implementation Tasks

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#36]
Implementation tasks should be created with respect to the requirements.Deadline: Sunday Midnight.

**Comment by hakansirin** [comment]
updated requirements file is up you have the flag now

**Comment by mehmetsefa2644** [comment]
Here is the [link of the google docs](https://docs.google.com/document/d/1RtbCg4hiDDPAnQHjov3_lq9frb2NdmyDHZkHvMS4YHs/edit?usp=sharing) that we will write our tasks. Please collaborate on the mission of writing tasks. 

**I want to mention that we will write the tasks according to the requirements**

**We are expected to finish writing our tasks this midnight(19.03.2017 23:59)**

**Comment by hakansirin** [comment]
New deadline is Saturday Midnight(25 May) 
Each task should have these properties:
1-Start Date
2-Finish Date
3-Duration(day)
3-How many people(optional)

**Comment by hakansirin** [comment]
Please share the merged tasks link(implementation and design tasks) with #39 as soon as you are done

**Comment by hakansirin** [comment]
https://github.com/bounswe/bounswe2015group8/wiki
https://drive.google.com/file/d/0B_8qE5vubTpuakZ1Zy1idkItTjg/view
here are some links that can help you start

**Comment by mrceyhun** [comment]
Guys, I wrote some tasks with [http://www.projectlibre.com/](http://www.projectlibre.com/) 14 days free application in **.pod** format. 
This is pdf view of tasks: 
[Cmpe352.pdf](https://github.com/bounswe/bounswe2017group1/files/872507/Cmpe352.pdf)

[Cmpe352.txt](https://github.com/bounswe/bounswe2017group1/files/872498/Cmpe352.txt)
I could not achieve .zip or .pod upload here. So I changed file-extension to ".txt". When you change the file extension ".pod" you open with **projectlibre**.
I did not finish, but i thing i can handle this night. Then I will send you for rectification.

**Comment by mrceyhun** [comment]
I commit project plan pod file and pdf file. Resource allocation and milestones are empty. After some correction and resource allocation (task sharing) on this plan, we can set milesones.
According to your reviews, we can create more stable version of project plan.

**Comment by mehmetsefa2644** [comment]
finished earlier
