### ISSUE TITLE
Milestone Defining

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#38]
After tasks are created, milestones should be defined.Deadline: next lecture.

**Comment by hakansirin** [comment]
@mrceyhun  Hello brother. I gave this holly mission to you. After all tasks are defined we should also create milestones. For this task all of our team count on you. 
A good time for a milestone is the time you got some deliverables like requirements.txt or end of class implementations etc. 
Each Milestone should have:
1- A date in DD/MM/YYYY format
2- A short description
2.1 - any deliverable or code file if it has any
2.2 - what part of the project finished etc. (no more than a line or 2) 

Here are some examples of milestones 
https://github.com/bounswe/bounswe2015group8/wiki
https://drive.google.com/file/d/0B_8qE5vubTpuakZ1Zy1idkItTjg/view

**Deadline Sunday Midnight (26 March)**

**Comment by hakansirin** [comment]
let #39 know when you are finished

**Comment by mrceyhun** [comment]
Milestones are defined in the ".pod" file.

**Comment by mrceyhun** [comment]
If you somebody save Project Plan.pod file as pdf, we can easily see the milesones.

**Comment by hakansirin** [comment]
Here we are again.
We did a meeting with @mrceyhun and @tahabayi  and created 3 milestone and further tasks. They are gonna be in the updated project plan and project plan that will be created by again @mrceyhun :)

**Comment by hakansirin** [comment]
@mrceyhun please close the issue after you updated the project diagram

**Comment by mehmetsefa2644** [comment]
Deadline of this issue was at March.
![bitmoji](https://render.bitstrips.com/v2/cpanel/9725180-322184509_2-s1-v1.png?transparent=1&palette=1&width=246)
