### ISSUE TITLE
Project Plan - Gant Chart

### ISSUE THREAD

**Issue by mehmetsefa2644** [bounswe/bounswe2017group1#39]
After all the tasks and milestones are prepared, project plan must be created. [We can use this to create the gant chart](https://www.matchware.com/free-trial?filename=mindview_en). Due date: next lecture.

**Comment by erkan309** [comment]
Thanks

**Comment by hakansirin** [comment]
@erkan309 you should have all necessary files to create a project plan till Sunday afternoon.
After you got all you can use any application you want, as long as we can edit that without you. Because we will continue to work on this project after you are gone. 
Your deadline is this week`s class

**Comment by hakansirin** [comment]
Of course you need to add project plan to our repository as a wiki page

**Comment by mehmetsefa2644** [comment]
finished earlier
