### ISSUE TITLE
Sequence Diagrams - add and display annotations.

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#44]
https://github.com/bounswe/bounswe2017group1/wiki/Class-Diagram
1- There are typos in the current diagrams 
2- Same functions needs parameters which is not currently added. Please check updated class diagram
https://github.com/bounswe/bounswe2017group1/wiki/Class-Diagram

**Comment by erkan309** [comment]
1. Typos done. pls check it.
2. I think you have a mistake in the numbering of annotations. You have to select a min. one heritage item but can only make a maximum one annotationt?

**Comment by hakansirin** [comment]
you are right about 2 ty.
for the first one,
function should not return functions,
in the first diagram:
1 userId is a variable not a function so it should not have parentheses at the end.
2 setDescription should have description and UserId parameters as corrected in the class diagram
similarly for displaying :
getDescription function call should return Description not setDescription function call
