### ISSUE TITLE
Software Deployment

### ISSUE THREAD

**Issue by mehmetgulsen** [bounswe/bounswe2017group1#75]
Get an AWS account and deploy the software. The operation system should be Ubuntu and the web platform should be Python/Django

**Comment by tahabayi** [comment]
Done.

**Comment by mrceyhun** [comment]
When should I close my AWS account. Are there any idea?

**Comment by hakansirin** [comment]
<img width="1484" alt="screen shot 2017-05-25 at 11 51 27 pm" src="https://cloud.githubusercontent.com/assets/13136199/26489212/277a23ce-420f-11e7-90a4-a62e110c1a83.png">

Since Cihat beyler used the API and saw it is working, I think it is safe to close
