### ISSUE TITLE
Project plan work distribution assignment

### ISSUE THREAD

**Issue by hakansirin** [bounswe/bounswe2017group1#82]
Hello all my friends,
We successfully updated the project diagram and divided the tasks however we need to decide who does which tasks. Best way to do it is meeting after the class time and divide the work depending on personal skills. See you all at the meeting tomorrow(27 sept) 2 pm

**Comment by mrceyhun** [comment]
[cmpe451.pdf](https://github.com/bounswe/bounswe2017group1/files/1340190/cmpe451.pdf)
